server:
  port: 8080
spring:
  application:
    #应用的名称,可选
    name: order_food
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: zh
  redis:
    host: 192.168.1.100
    port: 6379
    password: root
    database: 0
    cache:
      redis:
        time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
order_food:
  path: D:\img\
  mail:
    smtp_host: smtp.qq.com
    smtp_port: 587
    mail_user: 487888939@qq.com
    mail_password: rqirweuhspgpcaad
